version: '3.8'
services:
  publishing-agency:
    build: .
    container_name: mrf_agency_core
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - sovereign_network
    restart: always

networks:
  sovereign_network:
    external: true
